### PR TITLE
Add transformation to exclude shapes based on ShapeType

### PR DESCRIPTION
**Pull request by michael-mml**
Add a new transformation to support excluding shapes based on their ShapeType.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mtdowling** [comment]
What's the use case for this?

**Comment by michael-mml** [comment]
Our data model is populated from a variety of sources and clients are only interested in the data model itself, they do not care about the services, errors, or operations defined in our Smithy model. This transformation makes it easier to filter these out in a projection rather than tagging the unwanted shapes and using `ExcludeShapesByTag` transformation.

**Comment by mtdowling** [comment]
I think we should add a transforms called `ExcludeShapesBySelector` and `IncludeShapesBySelector`, which would allow us to use [Smithy selectors](https://awslabs.github.io/smithy/2.0/spec/selectors.html) to filter out or include shapes based on type, traits, members, and more complex logic. For example, you could exclude by type using `:is(service, operation)`. You could exclude shapes that aren't part of a specific service closure using `:not([id=some.id#Service] ~> *)`. We could potentially make existing related transforms just wrappers around the selector based transform (e.g., ExcludeShapeByTrait).

**Comment by sugmanue** [comment]
A more general approach was implemented in this [PR](https://github.com/awslabs/smithy/pull/1534). You can look at the docs for how to do either [inclusion](https://smithy.io/2.0/guides/building-models/build-config.html#includeshapesbyselector) or [exclusion](https://smithy.io/2.0/guides/building-models/build-config.html#excludeshapesbyselector) of shapes using a selector.

**Pull request closed without merging**
