### PR TITLE
Move traits to a single page

### PR DESCRIPTION
**Pull request by JordonPhillips**
This moves the non-aws trait definitions to a single page. To keep things somewhat simple in this pr, each previous page is now a template file, and all the template files are `include`'d. The only material change to the contents was to change the heading levels where necessary.

Additionally, the definition of the trait trait was moved onto this page.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mtdowling** [comment]
Something is funny with the `trait` trait. It's showing up under the "Traits" page, but also as a separate top-level entry in the Table of Contents.

image

**Comment by mtdowling** [comment]
image

That link links within the same document. Can be removed.

**Comment by JordonPhillips** [comment]
That seelaso link links to the description in the smithy model docs, not the trait trait on the same page

**Review by mtdowling — APPROVED** [review]

**Comment by JordonPhillips** [comment]
This seems to have been undone in a recent rebase, so I re-merged it.

**Pull request merged**
