### PR TITLE
Add references to operations and resources

### PR DESCRIPTION
**Pull request by srchase**
This PR adds service references to all operations and resources in the test models for the following projects:
* smithy-aws-traits
* smithy-linters
* smithy-model
* smithy-mqtt-traits

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mtdowling** [comment]
Why?

**Comment by srchase** [comment]
> Why?

This clears the way for adding a validator as described in #241

**Comment by kstich** [comment]
> > Why?
> 
> This clears the way for adding a validator as described in #241

Maybe the validator should only emit when a service shape exists in the model? If so, would we want something that emits when operations are found without a service at all?

**Comment by mtdowling** [comment]
> Maybe the validator should only emit when a service shape exists in the model?

+1

> If so, would we want something that emits when operations are found without a service at all?

I think it would be fine to find orphans with a shallow search. Is this operation referenced by a resource or service? Then don't emit. Is this resource referenced by a resource or service? Then don't emit. This would acheive the goal of detemining if an operation or resource is completely disconnected and forgotten to be bound somewhere. While it wouldn't tell you if an operation that's bound to a resource is disconnected from a service, it would tell you that it transitively is disconnected because the resouce it's connect to isn't bound to a service.

**Comment by srchase** [comment]
Updating models when introducing validator in #319.

**Pull request closed without merging**
